#! python


def build(ctx):

    # CHS Test Data Management
    for dataset in ['chs_test_ex2']:
        ctx(
            features='run_py_script',
            source='chs_example_data_management.py',
            deps=ctx.path_to(ctx, 'IN_DATA', '{}.dta'.format(dataset)),
            target=ctx.path_to(
                ctx, 'OUT_DATA', '{}_ready.dta'.format(dataset)),
            append=dataset
        )

    # fake data for ns_translog_model
    ctx(
        features='run_py_script',
        source='generate_fake_data.py',
        target=ctx.path_to(
            ctx, 'OUT_DATA', 'ns_translog_data.dta'))
